version: "3.3"

services:
  prometheus:
    image: prom/prometheus:v2.4.3
    container_name: 'prometheus'
    volumes:
      - ./config/prometheus/:/etc/prometheus/
    networks:
      - prometheus
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:6.6.2
    container_name: 'grafana'
    restart: unless-stopped
    networks:
      - grafana
    ports:
      - '3000:3000'
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=example
      - GF_SECURITY_ADMIN_PASSWORD=example
#    env_file:
#      - ./config/grafana/config.monitoring

networks:
  prometheus:
    external:
      name: gateway

  grafana:
    external:
      name: gateway
