version: '3.3'

services:

  mongo:
    image : mongo:4.2.3
    networks:
      - mongo
    volumes:
      - ./data/mongodb_data:/data/db
    ports:
      - 27017:27017

  postgres:
    build:
      context: ./database/postgre
    networks:
      - postgres
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
        - POSTGRES_MULTIPLE_DATABASES=authserver,datamaster
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image : redis:latest
    networks:
      - redis
    ports:
      - 6379:6379

networks:
  mongo:
    external:
      name: gateway
  postgres:
    external:
      name: gateway
  redis:
    external:
      name: gateway
